version: "3.8" 
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .env:/code/.env
    networks:
      - app-network

  web:
    build: ghcr.io/tyasemin/swe573:latest
    command: >
      sh -c "sleep 5 &&
             python manage.py migrate &&
             python create_superuser.py &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/codes
      - .env:/code/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    working_dir: /code
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
