version: "3.8" 
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: dotsdb
      POSTGRES_USER: dotsuser
      POSTGRES_PASSWORD: swe573dotsuser123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    command: >
      sh -c "sleep 5 &&
             python manage.py migrate &&
             python create_superuser.py &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
      - .env:/code/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    working_dir: /code
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
